---

- name: Suricata packages
  apt:
    name:
      - suricata
    state: present

- name: Suricata config file
  template:
    src: templates/suricata/suricata.yaml.j2
    dest: /etc/suricata/suricata.yaml
    owner: root
    group: root
    mode: 0644
  notify: suricata_restart

- name: Suricata disable.conf
  copy:
    src: files/disable.conf
    dest: /etc/suricata/disable.conf
    owner: root
    group: root
    mode: 0640
  notify: suricata_rules_update

- name: Schedule updates
  template:
    src: templates/suricata/update.cron
    dest: /etc/cron.d/suricata-rules-update
    owner: root
    group: root
    mode: 0644

- name: Suricata service
  service:
    name: suricata
    state: started
    enabled: true
